### ISSUE TITLE
Saving Kids with CSR SPI

### ISSUE THREAD

**Issue by BOOM-Mentoring** [Frans-Willem/CsrSpiDrivers#3]
Hi Frans-Willem

Great stuff! 

Would you be willing to share a little advice with a nonprofit educational program for teenagers in crisis? We work with kids on probation from jail, kids with drug problems, truant from school, or at risk for violence. Plz check out
theboom.org

We're developing a device based on the CSR chip (actually, the next gen QCC300x family). We want to program the chip without computer and without the USB dongle. Just SPI. 

NOT asking you to work with kids. Just some remote advice to our adult designers. 

Thx!
John

John Weiss, Director
The BOOM Mentoring
theboom.org

Read about us: boo.ma/makezine
Like us: facebook.com/bayviewboom
Follow us: twitter.com/bayviewboom
Donate: boo.ma/donate

415-68-WHEEL (415-689-4335)
c/o Renaissance Entrepreneurship Center
1325-B Evans Avenue
San Francisco, CA 94124

A project of Empowerment Works 501(c)3 Nonprofit Corporation
empowermentworks.org

**Comment by Frans-Willem** [comment]
Hi Jon,

Thanks for reaching out, but I'm currently not available for contract work.

Frans-Willem
